export const branches = [
    { code: 'RO', name: "Regional Office", category: null, emails: ["arifsheikh@nbp.com.pk", "ifra.khalid@nbp.com.pk", "almas.fazal@nbp.com.pk"] },
    { code: 341, name: "Main Branch Islamabad", category: 5, emails: ["Manager0341@nbp.com.pk", "opsmanager0341@nbp.com.pk", "Mars13@nbp.com.pk"] },
    { code: 376, name: "Main Branch Murree", category: 3, emails: ["manager0376@nbp.com.pk", "opsmanager0376@nbp.com.pk", "ibrahim.malik95@nbp.com.pk"] },
    { code: 474, name: "Foreign Office Branch", category: 4, emails: ["manager0474@nbp.com.pk", "opsmanager0474@nbp.com.pk", "Wasi29@nbp.com.pk"] },
    { code: 485, name: "S Block Branch", category: 3, emails: ["manager0485@nbp.com.pk", "opsmanager0485@nbp.com.pk", "Opsmanager0485@nbp.com.pk"] },
    { code: 501, name: "D-Block Branch", category: 3, emails: ["manager0501@nbp.com.pk", "opsmanager0501@nbp.com.pk", "shafaat.hussain@nbp.com.pk"] },
    { code: 565, name: "PINSTECH Nilore Branch", category: 4, emails: ["manager0565@nbp.com.pk", "opsmanager0565@nbp.com.pk", "Tabassum.raza@nbp.com.pk"] },
    { code: 692, name: "Ghora Gali Branch Murree", category: 3, emails: ["manager0692@nbp.com.pk", "azhar.hussain02@nbp.com.pk"] },
    { code: 812, name: "Phagwari Branch Murree", category: 2, emails: ["manager0812@nbp.com.pk", "Muhammad.safdar02@nbp.com.pk"] },
    { code: 854, name: "Super Market, Islamabad", category: 3, emails: ["manager0854@nbp.com.pk", "opsmanager0854@nbp.com.pk", "nasir.durani@nbp.com.pk"] },
    { code: 869, name: "Gulehra Gali Branch Murree", category: 3, emails: ["manager0869@nbp.com.pk", "Faizan.ali@nbp.com.pk"] },
    { code: 880, name: "B-Block Branch ", category: 3, emails: ["manager0880@nbp.com.pk", "opsmanager0880@nbp.com.pk", "tariqhamid@nbp.com.pk"] },
    { code: 882, name: "Blue Area Branch", category: 3, emails: ["manager0882@nbp.com.pk", "opsmanager0882@nbp.com.pk", "Zafar.usman@nbp.com.pk"] },
    { code: 977, name: "A.I.O.U Branch", category: 3, emails: ["manager0977@nbp.com.pk", "opsmanager0977@nbp.com.pk", "Faiz.muhammad01@nbp.com.pk"] },
    { code: 1456, name: "Aabpara Branch", category: 4, emails: ["manager1456@nbp.com.pk", "opsmanager1456@nbp.com.pk", "Shabnam.ghazala@nbp.com.pk"] },
    { code: 1469, name: "NHQ Branch Islamabad", category: 3, emails: ["manager1469@nbp.com.pk", "opsmanager1469@nbp.com.pk", "Muhammad.shoaib04@nbp.com.pk"] },
    { code: 1531, name: "Industrial Area Branch", category: 4, emails: ["manager1531@nbp.com.pk", "opsmanager1531@nbp.com.pk", "opsmanager@nbp.com.pk"] },
    { code: 1539, name: "P.A.R.C. Branch", category: 3, emails: ["manager1539@nbp.com.pk", "opsmanager1539@nbp.com.pk", "Maida.riaz@nbp.com.pk"] },
    { code: 1575, name: "Airport Branch Islamabad", category: 3, emails: ["manager1575@nbp.com.pk", "opsmanager1575@nbp.com.pk", "mzahid.sultan@nbp.com.pk"] },
    { code: 1628, name: "Jinnah Avenue Branch", category: 3, emails: ["manager1628@nbp.com.pk", "opsmanager1628@nbp.com.pk", "muhammad.basharat@nbp.com.pk"] },
    { code: 1654, name: "NIH Branch", category: 4, emails: ["manager1654@nbp.com.pk", "opsmanager1654@nbp.com.pk", "Muhammad.toqeer01@nbp.com.pk"] },
    { code: 1663, name: "Holiday Inn Branch", category: 3, emails: ["manager1663@nbp.com.pk", "opsmanager1663@nbp.com.pk", "nasirjanjua@nbp.com.pk"] },
    { code: 1694, name: "Al-Markaz  F-8 Branch", category: 4, emails: ["manager1694@nbp.com.pk", "opsmanager1694@nbp.com.pk"] },
    { code: 1725, name: "Margalla Branch", category: 5, emails: ["manager1725@nbp.com.pk", "opsmanager1725@nbp.com.pk", "jawad.wakil@nbp.com.pk"] },
    { code: 1732, name: "P.M Sectt. Branch", category: 4, emails: ["manager1732@nbp.com.pk", "opsmanager1732@nbp.com.pk", "mueed@nbp.com.pk"] },
    { code: 1932, name: "G-9 Branch Islamabad", category: 4, emails: ["manager1932@nbp.com.pk", "opsmanager1932@nbp.com.pk", "Sardar.ali01@nbp.com.pk"] },
    { code: 1933, name: "F-10 Branch Islamabad", category: 4, emails: ["manager1933@nbp.com.pk", "opsmanager1933@nbp.com.pk", "hameed.khan@nbp.com.pk"] },
    { code: 2067, name: "Tramri Chowk Branch", category: 3, emails: ["manager2067@nbp.com.pk", "opsmanager2067@nbp.com.pk", "naveed.hamayat@nbp.com.pk"] },
    { code: 2164, name: "G-10, Islamabad", category: 2, emails: ["manager2164@nbp.com.pk", "Muhammad.khan43@nbp.com.pk"] },
    { code: 2165, name: "DHA Phase - 1 Islamabad", category: 2, emails: ["manager2165@nbp.com.pk", "opsmanager2165@nbp.com.pk", "Bushra.zahid@nbp.com.pk"] },
    { code: 2168, name: "I-10 Markaz, Islamabad", category: 2, emails: ["manager2168@nbp.com.pk", "opsmanager2168@nbp.com.pk", "munir.qureshi@nbp.com.pk"] },
    { code: 2169, name: "Islamabad Stock Exchange", category: 2, emails: ["manager2169@nbp.com.pk", "AMINA.KHATOON@NBP.COM.PK"] },
    { code: 2297, name: "F-7 Markaz, Islamabad", category: 2, emails: ["manager2297@nbp.com.pk", "ahmad.nawaz02@nbp.com.pk"] },
    { code: 2309, name: "I-8 Markaz, Islamabad", category: 1, emails: ["manager2309@nbp.com.pk", "zulfiqar.ali21@nbp.com.pk"] },
    { code: 2323, name: "DHA Phase-II, Islamabad", category: 1, emails: ["manager2323@nbp.com.pk", "Hina.naz01@nbp.com.pk"] },
    { code: 2221, name: "Corporate Br. Islamabad", category: 5, emails: ["manager2221@nbp.com.pk", "Ehtisham.altaf@nbp.com.pk"] }
  ];